INFO - 2024-12-27 17:24:59,573 - uvicorn.error - __init__ - Will watch for changes in these directories: ['/home/uti/Documents/FastAPI/api/src']
INFO - 2024-12-27 17:24:59,574 - uvicorn.error - bind_socket - Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO - 2024-12-27 17:24:59,574 - uvicorn.error - startup - Started reloader process [206353] using WatchFiles
INFO - 2024-12-27 17:24:59,998 - uvicorn.error - _serve - Started server process [206367]
INFO - 2024-12-27 17:25:00,000 - uvicorn.error - startup - Waiting for application startup.
INFO - 2024-12-27 17:25:00,134 - fastapi - create_admin_account - Admin account with name elyte exist already
INFO - 2024-12-27 17:25:00,134 - fastapi - on_api_start - FastAPI Application: v1.0 is starting.
INFO - 2024-12-27 17:25:00,134 - uvicorn.error - startup - Application startup complete.
INFO - 2024-12-27 17:25:14,497 - uvicorn.error - shutdown - Shutting down
INFO - 2024-12-27 17:25:14,597 - uvicorn.error - shutdown - Waiting for application shutdown.
INFO - 2024-12-27 17:25:14,601 - fastapi - on_api_shuttdown - FastAPI Application: v1.0 is shutting down.
INFO - 2024-12-27 17:25:14,601 - uvicorn.error - shutdown - Application shutdown complete.
INFO - 2024-12-27 17:25:14,601 - uvicorn.error - _serve - Finished server process [206367]
INFO - 2024-12-27 17:25:14,604 - uvicorn.error - shutdown - Stopping reloader process [206353]
INFO - 2024-12-27 17:25:42,191 - uvicorn.error - __init__ - Will watch for changes in these directories: ['/home/uti/Documents/FastAPI/api/src']
INFO - 2024-12-27 17:25:42,191 - uvicorn.error - bind_socket - Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO - 2024-12-27 17:25:42,192 - uvicorn.error - startup - Started reloader process [206663] using WatchFiles
INFO - 2024-12-27 17:25:42,607 - uvicorn.error - _serve - Started server process [206676]
INFO - 2024-12-27 17:25:42,609 - uvicorn.error - startup - Waiting for application startup.
ERROR - 2024-12-27 17:25:42,747 - uvicorn.error - send - Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/main.py", line 29, in lifespan
    await handler.on_api_start()
  File "/home/uti/Documents/FastAPI/api/src/handler.py", line 14, in on_api_start
    await db.create_tables()
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 64, in create_tables
    await self.create_admin_account("elyte", self.async_session)
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 69, in create_admin_account
    if await self.get_user_by_username(admin_username) is None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 99, in get_user_by_username
    (user,) = users.first()
    ^^^^^^^
TypeError: cannot unpack non-iterable NoneType object

ERROR - 2024-12-27 17:25:42,748 - uvicorn.error - startup - Application startup failed. Exiting.
DEBUG - 2024-12-27 17:32:24,709 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:32:24,710 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
DEBUG - 2024-12-27 17:32:25,111 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.123619634521904'), (<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.123619634521904'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc')}
INFO - 2024-12-27 17:32:25,161 - uvicorn.error - _serve - Started server process [208437]
INFO - 2024-12-27 17:32:25,163 - uvicorn.error - startup - Waiting for application startup.
ERROR - 2024-12-27 17:32:25,320 - uvicorn.error - send - Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/main.py", line 29, in lifespan
    await handler.on_api_start()
  File "/home/uti/Documents/FastAPI/api/src/handler.py", line 14, in on_api_start
    await db.create_tables()
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 64, in create_tables
    await self.create_admin_account("elyte", self.async_session)
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 69, in create_admin_account
    if await self.get_user_by_username(admin_username) is None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 99, in get_user_by_username
    (user,) = users.first()
    ^^^^^^^
TypeError: cannot unpack non-iterable NoneType object

ERROR - 2024-12-27 17:32:25,321 - uvicorn.error - startup - Application startup failed. Exiting.
DEBUG - 2024-12-27 17:32:48,275 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:32:48,276 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
DEBUG - 2024-12-27 17:32:48,677 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.131551401928496'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.131551401928496'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc')}
INFO - 2024-12-27 17:32:48,714 - uvicorn.error - _serve - Started server process [208594]
INFO - 2024-12-27 17:32:48,716 - uvicorn.error - startup - Waiting for application startup.
ERROR - 2024-12-27 17:32:48,878 - uvicorn.error - send - Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/main.py", line 29, in lifespan
    await handler.on_api_start()
  File "/home/uti/Documents/FastAPI/api/src/handler.py", line 14, in on_api_start
    await db.create_tables()
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 64, in create_tables
    await self.create_admin_account("elyte", self.async_session)
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 69, in create_admin_account
    if await self.get_user_by_username(admin_username) is None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 99, in get_user_by_username
    (user,) = users.first()
    ^^^^^^^
TypeError: cannot unpack non-iterable NoneType object

ERROR - 2024-12-27 17:32:48,879 - uvicorn.error - startup - Application startup failed. Exiting.
DEBUG - 2024-12-27 17:32:54,540 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:32:54,540 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
DEBUG - 2024-12-27 17:32:54,942 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.140496848185136'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.140496848185136'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc')}
INFO - 2024-12-27 17:32:54,976 - uvicorn.error - _serve - Started server process [208689]
INFO - 2024-12-27 17:32:54,978 - uvicorn.error - startup - Waiting for application startup.
ERROR - 2024-12-27 17:32:55,145 - uvicorn.error - send - Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/main.py", line 29, in lifespan
    await handler.on_api_start()
  File "/home/uti/Documents/FastAPI/api/src/handler.py", line 14, in on_api_start
    await db.create_tables()
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 64, in create_tables
    await self.create_admin_account("elyte", self.async_session)
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 69, in create_admin_account
    if await self.get_user_by_username(admin_username) is None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 98, in get_user_by_username
    (user,) = users.first()
    ^^^^^^^
TypeError: cannot unpack non-iterable NoneType object

ERROR - 2024-12-27 17:32:55,147 - uvicorn.error - startup - Application startup failed. Exiting.
DEBUG - 2024-12-27 17:33:16,345 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:33:16,345 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
DEBUG - 2024-12-27 17:33:16,747 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.128409189967664'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc'), (<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.128409189967664')}
INFO - 2024-12-27 17:33:16,777 - uvicorn.error - _serve - Started server process [208825]
INFO - 2024-12-27 17:33:16,779 - uvicorn.error - startup - Waiting for application startup.
ERROR - 2024-12-27 17:33:16,947 - uvicorn.error - send - Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/main.py", line 29, in lifespan
    await handler.on_api_start()
  File "/home/uti/Documents/FastAPI/api/src/handler.py", line 14, in on_api_start
    await db.create_tables()
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 64, in create_tables
    await self.create_admin_account("elyte", self.async_session)
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 69, in create_admin_account
    if await self.get_user_by_username(admin_username) is None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 98, in get_user_by_username
    (user,) = users.first()
    ^^^^^^^
TypeError: cannot unpack non-iterable NoneType object

ERROR - 2024-12-27 17:33:16,948 - uvicorn.error - startup - Application startup failed. Exiting.
DEBUG - 2024-12-27 17:33:20,906 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:33:20,906 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
DEBUG - 2024-12-27 17:33:21,307 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.135062190597936'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.135062190597936'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc')}
INFO - 2024-12-27 17:33:21,360 - uvicorn.error - _serve - Started server process [208904]
INFO - 2024-12-27 17:33:21,362 - uvicorn.error - startup - Waiting for application startup.
INFO - 2024-12-27 17:33:21,486 - fastapi - create_admin_account - account with id 751a9771-f82e-4874-8cbe-111bedb24750 created
INFO - 2024-12-27 17:33:21,486 - fastapi - create_admin_account - Admin account with name elyte exist already
INFO - 2024-12-27 17:33:21,486 - fastapi - on_api_start - FastAPI Application: v1.0 is starting.
INFO - 2024-12-27 17:33:21,486 - uvicorn.error - startup - Application startup complete.
DEBUG - 2024-12-27 17:34:34,710 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:34:34,711 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
INFO - 2024-12-27 17:34:34,717 - uvicorn.error - shutdown - Shutting down
INFO - 2024-12-27 17:34:34,818 - uvicorn.error - shutdown - Waiting for application shutdown.
INFO - 2024-12-27 17:34:34,821 - fastapi - on_api_shuttdown - FastAPI Application: v1.0 is shutting down.
INFO - 2024-12-27 17:34:34,822 - uvicorn.error - shutdown - Application shutdown complete.
INFO - 2024-12-27 17:34:34,822 - uvicorn.error - _serve - Finished server process [208904]
DEBUG - 2024-12-27 17:34:35,227 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.132330345719600'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc'), (<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.132330345719600')}
INFO - 2024-12-27 17:34:35,261 - uvicorn.error - _serve - Started server process [209275]
INFO - 2024-12-27 17:34:35,263 - uvicorn.error - startup - Waiting for application startup.
INFO - 2024-12-27 17:34:35,415 - fastapi - create_admin_account - account with id c1c3864d-4153-4849-a079-0fb8749b7b24 created
INFO - 2024-12-27 17:34:35,415 - fastapi - create_admin_account - Admin account with name elyte exist already
INFO - 2024-12-27 17:34:35,415 - fastapi - on_api_start - FastAPI Application: v1.0 is starting.
INFO - 2024-12-27 17:34:35,415 - uvicorn.error - startup - Application startup complete.
DEBUG - 2024-12-27 17:34:41,042 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:34:41,042 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
INFO - 2024-12-27 17:34:41,135 - uvicorn.error - shutdown - Shutting down
INFO - 2024-12-27 17:34:41,236 - uvicorn.error - shutdown - Waiting for application shutdown.
INFO - 2024-12-27 17:34:41,240 - fastapi - on_api_shuttdown - FastAPI Application: v1.0 is shutting down.
INFO - 2024-12-27 17:34:41,240 - uvicorn.error - shutdown - Application shutdown complete.
INFO - 2024-12-27 17:34:41,240 - uvicorn.error - _serve - Finished server process [209275]
DEBUG - 2024-12-27 17:34:41,645 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.130543339923248'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc'), (<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.130543339923248')}
INFO - 2024-12-27 17:34:41,669 - uvicorn.error - _serve - Started server process [209375]
INFO - 2024-12-27 17:34:41,671 - uvicorn.error - startup - Waiting for application startup.
INFO - 2024-12-27 17:34:41,819 - fastapi - create_admin_account - account with id f7f1b1a0-f84b-48c0-a8b3-9393c8302278 created
INFO - 2024-12-27 17:34:41,819 - fastapi - create_admin_account - Admin account with name elyte exist already
INFO - 2024-12-27 17:34:41,820 - fastapi - on_api_start - FastAPI Application: v1.0 is starting.
INFO - 2024-12-27 17:34:41,820 - uvicorn.error - startup - Application startup complete.
DEBUG - 2024-12-27 17:34:42,547 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:34:42,547 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
INFO - 2024-12-27 17:34:42,622 - uvicorn.error - shutdown - Shutting down
INFO - 2024-12-27 17:34:42,723 - uvicorn.error - shutdown - Waiting for application shutdown.
INFO - 2024-12-27 17:34:42,726 - fastapi - on_api_shuttdown - FastAPI Application: v1.0 is shutting down.
INFO - 2024-12-27 17:34:42,726 - uvicorn.error - shutdown - Application shutdown complete.
INFO - 2024-12-27 17:34:42,726 - uvicorn.error - _serve - Finished server process [209375]
DEBUG - 2024-12-27 17:34:43,131 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc'), (<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.123285534943024'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.123285534943024')}
INFO - 2024-12-27 17:34:43,180 - uvicorn.error - _serve - Started server process [209399]
INFO - 2024-12-27 17:34:43,183 - uvicorn.error - startup - Waiting for application startup.
INFO - 2024-12-27 17:34:43,323 - fastapi - create_admin_account - account with id 1c871c30-5691-431c-8364-25d2e7240975 created
INFO - 2024-12-27 17:34:43,324 - fastapi - create_admin_account - Admin account with name elyte exist already
INFO - 2024-12-27 17:34:43,324 - fastapi - on_api_start - FastAPI Application: v1.0 is starting.
INFO - 2024-12-27 17:34:43,324 - uvicorn.error - startup - Application startup complete.
DEBUG - 2024-12-27 17:35:02,188 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:35:02,189 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
INFO - 2024-12-27 17:35:02,277 - uvicorn.error - shutdown - Shutting down
INFO - 2024-12-27 17:35:02,378 - uvicorn.error - shutdown - Waiting for application shutdown.
INFO - 2024-12-27 17:35:02,381 - fastapi - on_api_shuttdown - FastAPI Application: v1.0 is shutting down.
INFO - 2024-12-27 17:35:02,382 - uvicorn.error - shutdown - Application shutdown complete.
INFO - 2024-12-27 17:35:02,382 - uvicorn.error - _serve - Finished server process [209399]
DEBUG - 2024-12-27 17:35:02,788 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc'), (<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.127006371227440'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.127006371227440')}
INFO - 2024-12-27 17:35:02,813 - uvicorn.error - _serve - Started server process [209535]
INFO - 2024-12-27 17:35:02,815 - uvicorn.error - startup - Waiting for application startup.
INFO - 2024-12-27 17:35:02,851 - fastapi - create_admin_account - Admin account with name elyte exist already
INFO - 2024-12-27 17:35:02,851 - fastapi - on_api_start - FastAPI Application: v1.0 is starting.
INFO - 2024-12-27 17:35:02,851 - uvicorn.error - startup - Application startup complete.
DEBUG - 2024-12-27 17:35:14,726 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:35:14,726 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
INFO - 2024-12-27 17:35:14,800 - uvicorn.error - shutdown - Shutting down
INFO - 2024-12-27 17:35:14,901 - uvicorn.error - shutdown - Waiting for application shutdown.
INFO - 2024-12-27 17:35:14,901 - fastapi - on_api_shuttdown - FastAPI Application: v1.0 is shutting down.
INFO - 2024-12-27 17:35:14,902 - uvicorn.error - shutdown - Application shutdown complete.
INFO - 2024-12-27 17:35:14,902 - uvicorn.error - _serve - Finished server process [209535]
DEBUG - 2024-12-27 17:35:15,307 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.124185677735728'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.124185677735728'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc')}
INFO - 2024-12-27 17:35:15,339 - uvicorn.error - _serve - Started server process [209641]
INFO - 2024-12-27 17:35:15,341 - uvicorn.error - startup - Waiting for application startup.
INFO - 2024-12-27 17:35:15,485 - fastapi - create_admin_account - account with id 1e8b60b8-4b7f-4a1d-b6bb-3679ab83554c created
INFO - 2024-12-27 17:35:15,485 - fastapi - create_admin_account - Admin account with name elyte exist already
INFO - 2024-12-27 17:35:15,485 - fastapi - on_api_start - FastAPI Application: v1.0 is starting.
INFO - 2024-12-27 17:35:15,485 - uvicorn.error - startup - Application startup complete.
DEBUG - 2024-12-27 17:39:03,894 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:39:03,894 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
INFO - 2024-12-27 17:39:03,934 - uvicorn.error - shutdown - Shutting down
INFO - 2024-12-27 17:39:04,035 - uvicorn.error - shutdown - Waiting for application shutdown.
INFO - 2024-12-27 17:39:04,038 - fastapi - on_api_shuttdown - FastAPI Application: v1.0 is shutting down.
INFO - 2024-12-27 17:39:04,038 - uvicorn.error - shutdown - Application shutdown complete.
INFO - 2024-12-27 17:39:04,038 - uvicorn.error - _serve - Finished server process [209641]
DEBUG - 2024-12-27 17:39:04,444 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.130563650234160'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.130563650234160'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc')}
INFO - 2024-12-27 17:39:04,478 - uvicorn.error - _serve - Started server process [210667]
INFO - 2024-12-27 17:39:04,480 - uvicorn.error - startup - Waiting for application startup.
INFO - 2024-12-27 17:39:04,618 - fastapi - create_admin_account - account with id acf13142-3c68-4a6a-beb4-b71116797137 created
INFO - 2024-12-27 17:39:04,618 - fastapi - create_admin_account - Admin account with name elyte exist already
INFO - 2024-12-27 17:39:04,618 - fastapi - on_api_start - FastAPI Application: v1.0 is starting.
INFO - 2024-12-27 17:39:04,618 - uvicorn.error - startup - Application startup complete.
DEBUG - 2024-12-27 17:39:07,951 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:39:07,952 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
INFO - 2024-12-27 17:39:08,027 - uvicorn.error - shutdown - Shutting down
INFO - 2024-12-27 17:39:08,127 - uvicorn.error - shutdown - Waiting for application shutdown.
INFO - 2024-12-27 17:39:08,130 - fastapi - on_api_shuttdown - FastAPI Application: v1.0 is shutting down.
INFO - 2024-12-27 17:39:08,130 - uvicorn.error - shutdown - Application shutdown complete.
INFO - 2024-12-27 17:39:08,131 - uvicorn.error - _serve - Finished server process [210667]
DEBUG - 2024-12-27 17:39:08,538 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.130216246093616'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.130216246093616'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc')}
INFO - 2024-12-27 17:39:08,577 - uvicorn.error - _serve - Started server process [210707]
INFO - 2024-12-27 17:39:08,579 - uvicorn.error - startup - Waiting for application startup.
INFO - 2024-12-27 17:39:08,713 - fastapi - create_admin_account - account with id af5e40f4-4c52-470c-bf91-3806c3d2a6db created
INFO - 2024-12-27 17:39:08,713 - fastapi - create_admin_account - Admin account with name elyte exist already
INFO - 2024-12-27 17:39:08,713 - fastapi - on_api_start - FastAPI Application: v1.0 is starting.
INFO - 2024-12-27 17:39:08,713 - uvicorn.error - startup - Application startup complete.
DEBUG - 2024-12-27 17:39:10,393 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:39:10,393 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
INFO - 2024-12-27 17:39:10,418 - uvicorn.error - shutdown - Shutting down
INFO - 2024-12-27 17:39:10,519 - uvicorn.error - shutdown - Waiting for application shutdown.
INFO - 2024-12-27 17:39:10,522 - fastapi - on_api_shuttdown - FastAPI Application: v1.0 is shutting down.
INFO - 2024-12-27 17:39:10,522 - uvicorn.error - shutdown - Application shutdown complete.
INFO - 2024-12-27 17:39:10,522 - uvicorn.error - _serve - Finished server process [210707]
DEBUG - 2024-12-27 17:39:10,928 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.126350580475696'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.126350580475696'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc')}
INFO - 2024-12-27 17:39:10,968 - uvicorn.error - _serve - Started server process [210774]
INFO - 2024-12-27 17:39:10,970 - uvicorn.error - startup - Waiting for application startup.
INFO - 2024-12-27 17:39:11,111 - fastapi - create_admin_account - account with id 002a75ba-8f7b-495e-8769-809514700151 created
INFO - 2024-12-27 17:39:11,112 - fastapi - create_admin_account - Admin account with name elyte exist already
INFO - 2024-12-27 17:39:11,112 - fastapi - on_api_start - FastAPI Application: v1.0 is starting.
INFO - 2024-12-27 17:39:11,112 - uvicorn.error - startup - Application startup complete.
DEBUG - 2024-12-27 17:39:20,403 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:39:20,404 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
INFO - 2024-12-27 17:39:20,439 - uvicorn.error - shutdown - Shutting down
INFO - 2024-12-27 17:39:20,540 - uvicorn.error - shutdown - Waiting for application shutdown.
INFO - 2024-12-27 17:39:20,543 - fastapi - on_api_shuttdown - FastAPI Application: v1.0 is shutting down.
INFO - 2024-12-27 17:39:20,543 - uvicorn.error - shutdown - Application shutdown complete.
INFO - 2024-12-27 17:39:20,543 - uvicorn.error - _serve - Finished server process [210774]
DEBUG - 2024-12-27 17:39:20,948 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.127027226830640'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.127027226830640'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc')}
INFO - 2024-12-27 17:39:20,989 - uvicorn.error - _serve - Started server process [210868]
INFO - 2024-12-27 17:39:20,991 - uvicorn.error - startup - Waiting for application startup.
INFO - 2024-12-27 17:39:21,149 - fastapi - create_admin_account - account with id 784b2b24-d1c2-451e-86b7-7286f5098811 created
INFO - 2024-12-27 17:39:21,149 - fastapi - create_admin_account - Admin account with name elyte exist already
INFO - 2024-12-27 17:39:21,149 - fastapi - on_api_start - FastAPI Application: v1.0 is starting.
INFO - 2024-12-27 17:39:21,149 - uvicorn.error - startup - Application startup complete.
DEBUG - 2024-12-27 17:39:22,652 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:39:22,652 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
INFO - 2024-12-27 17:39:22,655 - uvicorn.error - shutdown - Shutting down
INFO - 2024-12-27 17:39:22,755 - uvicorn.error - shutdown - Waiting for application shutdown.
INFO - 2024-12-27 17:39:22,758 - fastapi - on_api_shuttdown - FastAPI Application: v1.0 is shutting down.
INFO - 2024-12-27 17:39:22,758 - uvicorn.error - shutdown - Application shutdown complete.
INFO - 2024-12-27 17:39:22,759 - uvicorn.error - _serve - Finished server process [210868]
DEBUG - 2024-12-27 17:39:25,117 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:39:25,118 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
DEBUG - 2024-12-27 17:39:25,519 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.133087438022448'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.133087438022448')}
INFO - 2024-12-27 17:39:25,573 - uvicorn.error - _serve - Started server process [210929]
INFO - 2024-12-27 17:39:25,575 - uvicorn.error - startup - Waiting for application startup.
ERROR - 2024-12-27 17:39:25,731 - uvicorn.error - send - Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/main.py", line 29, in lifespan
    await handler.on_api_start()
  File "/home/uti/Documents/FastAPI/api/src/handler.py", line 14, in on_api_start
    await db.create_tables()
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 64, in create_tables
    await self.create_admin_account("elyte", self.async_session)
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 69, in create_admin_account
    print(self.cf.conct)
          ^^^^^^^^^^^^^
AttributeError: 'ApiConfig' object has no attribute 'conct'

ERROR - 2024-12-27 17:39:25,733 - uvicorn.error - startup - Application startup failed. Exiting.
DEBUG - 2024-12-27 17:39:26,421 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:39:26,421 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
DEBUG - 2024-12-27 17:39:26,823 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.139084605892400'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.139084605892400'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc')}
INFO - 2024-12-27 17:39:26,868 - uvicorn.error - _serve - Started server process [210942]
INFO - 2024-12-27 17:39:26,870 - uvicorn.error - startup - Waiting for application startup.
ERROR - 2024-12-27 17:39:27,025 - uvicorn.error - send - Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/main.py", line 29, in lifespan
    await handler.on_api_start()
  File "/home/uti/Documents/FastAPI/api/src/handler.py", line 14, in on_api_start
    await db.create_tables()
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 64, in create_tables
    await self.create_admin_account("elyte", self.async_session)
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 69, in create_admin_account
    print(self.cf.con)
          ^^^^^^^^^^^
AttributeError: 'ApiConfig' object has no attribute 'con'

ERROR - 2024-12-27 17:39:27,026 - uvicorn.error - startup - Application startup failed. Exiting.
DEBUG - 2024-12-27 17:39:28,225 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:39:28,225 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
DEBUG - 2024-12-27 17:39:28,627 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.130841648097072'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.130841648097072')}
INFO - 2024-12-27 17:39:28,671 - uvicorn.error - _serve - Started server process [210969]
INFO - 2024-12-27 17:39:28,673 - uvicorn.error - startup - Waiting for application startup.
INFO - 2024-12-27 17:39:28,866 - fastapi - create_admin_account - account with id 7f87be56-1350-44b0-9eea-2bffe64c6053 created
INFO - 2024-12-27 17:39:28,866 - fastapi - create_admin_account - Admin account with name elyte exist already
INFO - 2024-12-27 17:39:28,866 - fastapi - on_api_start - FastAPI Application: v1.0 is starting.
INFO - 2024-12-27 17:39:28,866 - uvicorn.error - startup - Application startup complete.
DEBUG - 2024-12-27 17:40:23,803 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/pyproject.toml')}
DEBUG - 2024-12-27 17:40:58,752 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/pyproject.toml')}
DEBUG - 2024-12-27 17:41:01,108 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/pyproject.toml')}
DEBUG - 2024-12-27 17:41:02,712 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/pyproject.toml')}
DEBUG - 2024-12-27 17:41:07,979 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/pyproject.toml')}
DEBUG - 2024-12-27 17:41:09,635 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/pyproject.toml')}
DEBUG - 2024-12-27 17:41:11,890 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/pyproject.toml')}
INFO - 2024-12-27 17:41:24,839 - uvicorn.error - shutdown - Shutting down
INFO - 2024-12-27 17:41:24,940 - uvicorn.error - shutdown - Waiting for application shutdown.
INFO - 2024-12-27 17:41:24,943 - fastapi - on_api_shuttdown - FastAPI Application: v1.0 is shutting down.
INFO - 2024-12-27 17:41:24,943 - uvicorn.error - shutdown - Application shutdown complete.
INFO - 2024-12-27 17:41:24,943 - uvicorn.error - _serve - Finished server process [210969]
INFO - 2024-12-27 17:41:24,948 - uvicorn.error - shutdown - Stopping reloader process [206663]
INFO - 2024-12-27 17:41:26,802 - uvicorn.error - __init__ - Will watch for changes in these directories: ['/home/uti/Documents/FastAPI/api/src']
INFO - 2024-12-27 17:41:26,803 - uvicorn.error - bind_socket - Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO - 2024-12-27 17:41:26,803 - uvicorn.error - startup - Started reloader process [211917] using WatchFiles
INFO - 2024-12-27 17:41:27,221 - uvicorn.error - _serve - Started server process [211919]
INFO - 2024-12-27 17:41:27,223 - uvicorn.error - startup - Waiting for application startup.
INFO - 2024-12-27 17:41:27,370 - fastapi - create_admin_account - account with id b82693b2-e9b7-4b01-86aa-e4d92cdc27e1 created
INFO - 2024-12-27 17:41:27,370 - fastapi - create_admin_account - Admin account with name elyte exist already
INFO - 2024-12-27 17:41:27,370 - fastapi - on_api_start - FastAPI Application: v1.0 is starting.
INFO - 2024-12-27 17:41:27,370 - uvicorn.error - startup - Application startup complete.
DEBUG - 2024-12-27 17:43:47,780 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/pyproject.toml')}
DEBUG - 2024-12-27 17:43:49,584 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/pyproject.toml')}
DEBUG - 2024-12-27 17:44:14,973 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/pyproject.toml')}
DEBUG - 2024-12-27 17:44:26,307 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/pyproject.toml')}
DEBUG - 2024-12-27 17:45:35,166 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:45:35,167 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
INFO - 2024-12-27 17:45:35,181 - uvicorn.error - shutdown - Shutting down
INFO - 2024-12-27 17:45:35,282 - uvicorn.error - shutdown - Waiting for application shutdown.
INFO - 2024-12-27 17:45:35,285 - fastapi - on_api_shuttdown - FastAPI Application: v1.0 is shutting down.
INFO - 2024-12-27 17:45:35,285 - uvicorn.error - shutdown - Application shutdown complete.
INFO - 2024-12-27 17:45:35,286 - uvicorn.error - _serve - Finished server process [211919]
DEBUG - 2024-12-27 17:45:37,897 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:45:37,898 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
DEBUG - 2024-12-27 17:45:38,299 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.139078354281904'), (<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.139078354281904')}
INFO - 2024-12-27 17:45:38,329 - uvicorn.error - _serve - Started server process [213884]
INFO - 2024-12-27 17:45:38,331 - uvicorn.error - startup - Waiting for application startup.
ERROR - 2024-12-27 17:45:38,486 - uvicorn.error - send - Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/main.py", line 29, in lifespan
    await handler.on_api_start()
  File "/home/uti/Documents/FastAPI/api/src/handler.py", line 14, in on_api_start
    await db.create_tables()
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 64, in create_tables
    await self.create_admin_account("elyte", self.async_session)
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 69, in create_admin_account
    print(self.cf.contacts[''])
          ~~~~~~~~~~~~~~~~^^^^
KeyError: ''

ERROR - 2024-12-27 17:45:38,487 - uvicorn.error - startup - Application startup failed. Exiting.
DEBUG - 2024-12-27 17:45:45,974 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:45:45,975 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
DEBUG - 2024-12-27 17:45:46,376 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.124722244986288'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc'), (<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.124722244986288')}
INFO - 2024-12-27 17:45:46,406 - uvicorn.error - _serve - Started server process [213964]
INFO - 2024-12-27 17:45:46,408 - uvicorn.error - startup - Waiting for application startup.
INFO - 2024-12-27 17:45:46,580 - fastapi - create_admin_account - account with id 0630fa07-a726-4240-a182-f5bf1e266957 created
INFO - 2024-12-27 17:45:46,580 - fastapi - create_admin_account - Admin account with name elyte exist already
INFO - 2024-12-27 17:45:46,580 - fastapi - on_api_start - FastAPI Application: v1.0 is starting.
INFO - 2024-12-27 17:45:46,580 - uvicorn.error - startup - Application startup complete.
DEBUG - 2024-12-27 17:46:29,822 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:46:29,823 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
INFO - 2024-12-27 17:46:29,917 - uvicorn.error - shutdown - Shutting down
INFO - 2024-12-27 17:46:30,017 - uvicorn.error - shutdown - Waiting for application shutdown.
INFO - 2024-12-27 17:46:30,020 - fastapi - on_api_shuttdown - FastAPI Application: v1.0 is shutting down.
INFO - 2024-12-27 17:46:30,020 - uvicorn.error - shutdown - Application shutdown complete.
INFO - 2024-12-27 17:46:30,021 - uvicorn.error - _serve - Finished server process [213964]
DEBUG - 2024-12-27 17:46:30,426 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.123289864922544'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.123289864922544')}
INFO - 2024-12-27 17:46:30,453 - uvicorn.error - _serve - Started server process [214228]
INFO - 2024-12-27 17:46:30,455 - uvicorn.error - startup - Waiting for application startup.
ERROR - 2024-12-27 17:46:30,629 - uvicorn.error - send - Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/main.py", line 29, in lifespan
    await handler.on_api_start()
  File "/home/uti/Documents/FastAPI/api/src/handler.py", line 14, in on_api_start
    await db.create_tables()
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 64, in create_tables
    await self.create_admin_account(self.async_session)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AsyncDatabaseSession.create_admin_account() missing 1 required positional argument: 'async_session'

ERROR - 2024-12-27 17:46:30,630 - uvicorn.error - startup - Application startup failed. Exiting.
DEBUG - 2024-12-27 17:46:47,270 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:46:47,270 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
DEBUG - 2024-12-27 17:46:47,671 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.128442794124720'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc'), (<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.128442794124720')}
INFO - 2024-12-27 17:46:47,715 - uvicorn.error - _serve - Started server process [214341]
INFO - 2024-12-27 17:46:47,717 - uvicorn.error - startup - Waiting for application startup.
ERROR - 2024-12-27 17:46:47,870 - uvicorn.error - send - Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/main.py", line 29, in lifespan
    await handler.on_api_start()
  File "/home/uti/Documents/FastAPI/api/src/handler.py", line 14, in on_api_start
    await db.create_tables()
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 64, in create_tables
    await self.create_admin_account(self.async_session)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AsyncDatabaseSession.create_admin_account() missing 1 required positional argument: 'async_session'

ERROR - 2024-12-27 17:46:47,871 - uvicorn.error - startup - Application startup failed. Exiting.
DEBUG - 2024-12-27 17:47:22,161 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:47:22,161 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
DEBUG - 2024-12-27 17:47:22,563 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.129047803176368'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc'), (<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.129047803176368')}
INFO - 2024-12-27 17:47:22,604 - uvicorn.error - _serve - Started server process [214582]
INFO - 2024-12-27 17:47:22,606 - uvicorn.error - startup - Waiting for application startup.
ERROR - 2024-12-27 17:47:22,756 - uvicorn.error - send - Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/main.py", line 29, in lifespan
    await handler.on_api_start()
  File "/home/uti/Documents/FastAPI/api/src/handler.py", line 14, in on_api_start
    await db.create_tables()
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 64, in create_tables
    await self.create_admin_account(self.async_session)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AsyncDatabaseSession.create_admin_account() missing 1 required positional argument: 'async_session'

ERROR - 2024-12-27 17:47:22,757 - uvicorn.error - startup - Application startup failed. Exiting.
DEBUG - 2024-12-27 17:47:35,454 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:47:35,454 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
DEBUG - 2024-12-27 17:47:35,855 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.128805507655088'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc'), (<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.128805507655088')}
INFO - 2024-12-27 17:47:35,875 - uvicorn.error - _serve - Started server process [214699]
INFO - 2024-12-27 17:47:35,877 - uvicorn.error - startup - Waiting for application startup.
ERROR - 2024-12-27 17:47:36,046 - uvicorn.error - send - Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/main.py", line 29, in lifespan
    await handler.on_api_start()
  File "/home/uti/Documents/FastAPI/api/src/handler.py", line 14, in on_api_start
    await db.create_tables()
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 64, in create_tables
    await self.create_admin_account(self.async_session)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AsyncDatabaseSession.create_admin_account() missing 1 required positional argument: 'async_session'

ERROR - 2024-12-27 17:47:36,047 - uvicorn.error - startup - Application startup failed. Exiting.
DEBUG - 2024-12-27 17:47:39,267 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:47:39,267 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
DEBUG - 2024-12-27 17:47:39,668 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.124181655397808'), (<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.124181655397808')}
INFO - 2024-12-27 17:47:39,690 - uvicorn.error - _serve - Started server process [214771]
INFO - 2024-12-27 17:47:39,692 - uvicorn.error - startup - Waiting for application startup.
ERROR - 2024-12-27 17:47:39,829 - uvicorn.error - send - Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/main.py", line 29, in lifespan
    await handler.on_api_start()
  File "/home/uti/Documents/FastAPI/api/src/handler.py", line 14, in on_api_start
    await db.create_tables()
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 64, in create_tables
    await self.create_admin_account(self.async_session)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AsyncDatabaseSession.create_admin_account() missing 1 required positional argument: 'async_session'

ERROR - 2024-12-27 17:47:39,831 - uvicorn.error - startup - Application startup failed. Exiting.
DEBUG - 2024-12-27 17:47:40,973 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:47:40,973 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
DEBUG - 2024-12-27 17:47:41,374 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.140516326794672'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc'), (<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.140516326794672')}
INFO - 2024-12-27 17:47:41,413 - uvicorn.error - _serve - Started server process [214786]
INFO - 2024-12-27 17:47:41,415 - uvicorn.error - startup - Waiting for application startup.
ERROR - 2024-12-27 17:47:41,580 - uvicorn.error - send - Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/main.py", line 29, in lifespan
    await handler.on_api_start()
  File "/home/uti/Documents/FastAPI/api/src/handler.py", line 14, in on_api_start
    await db.create_tables()
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 64, in create_tables
    await self.create_admin_account(self.async_session)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AsyncDatabaseSession.create_admin_account() missing 1 required positional argument: 'async_session'

ERROR - 2024-12-27 17:47:41,582 - uvicorn.error - startup - Application startup failed. Exiting.
DEBUG - 2024-12-27 17:47:42,979 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:47:42,980 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
DEBUG - 2024-12-27 17:47:43,331 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc'), (<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.129805710763440'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.129805710763440')}
INFO - 2024-12-27 17:47:43,402 - uvicorn.error - _serve - Started server process [214829]
INFO - 2024-12-27 17:47:43,404 - uvicorn.error - startup - Waiting for application startup.
ERROR - 2024-12-27 17:47:43,555 - uvicorn.error - send - Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/main.py", line 29, in lifespan
    await handler.on_api_start()
  File "/home/uti/Documents/FastAPI/api/src/handler.py", line 14, in on_api_start
    await db.create_tables()
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 64, in create_tables
    await self.create_admin_account(self.async_session)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AsyncDatabaseSession.create_admin_account() missing 1 required positional argument: 'async_session'

ERROR - 2024-12-27 17:47:43,556 - uvicorn.error - startup - Application startup failed. Exiting.
DEBUG - 2024-12-27 17:48:09,221 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:48:09,221 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
DEBUG - 2024-12-27 17:48:09,622 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.137750216844720'), (<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.137750216844720')}
INFO - 2024-12-27 17:48:09,670 - uvicorn.error - _serve - Started server process [214986]
INFO - 2024-12-27 17:48:09,672 - uvicorn.error - startup - Waiting for application startup.
ERROR - 2024-12-27 17:48:09,819 - uvicorn.error - send - Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/main.py", line 29, in lifespan
    await handler.on_api_start()
  File "/home/uti/Documents/FastAPI/api/src/handler.py", line 14, in on_api_start
    await db.create_tables()
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 64, in create_tables
    await self.create_admin_account(self.async_session)
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 70, in create_admin_account
    if await self.get_user_by_username(admin_username) is None:
                                       ^^^^^^^^^^^^^^
NameError: name 'admin_username' is not defined

ERROR - 2024-12-27 17:48:09,821 - uvicorn.error - startup - Application startup failed. Exiting.
DEBUG - 2024-12-27 17:48:27,019 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:48:27,019 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
DEBUG - 2024-12-27 17:48:27,421 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.137147517789616'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.137147517789616'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc')}
INFO - 2024-12-27 17:48:27,443 - uvicorn.error - _serve - Started server process [215091]
INFO - 2024-12-27 17:48:27,445 - uvicorn.error - startup - Waiting for application startup.
ERROR - 2024-12-27 17:48:27,614 - uvicorn.error - send - Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/main.py", line 29, in lifespan
    await handler.on_api_start()
  File "/home/uti/Documents/FastAPI/api/src/handler.py", line 14, in on_api_start
    await db.create_tables()
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 64, in create_tables
    await self.create_admin_account(self.async_session)
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 80, in create_admin_account
    created_by=admin_username,
               ^^^^^^^^^^^^^^
NameError: name 'admin_username' is not defined

ERROR - 2024-12-27 17:48:27,616 - uvicorn.error - startup - Application startup failed. Exiting.
DEBUG - 2024-12-27 17:48:32,085 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:48:32,085 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
DEBUG - 2024-12-27 17:48:32,486 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.139950398318000'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.139950398318000'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc')}
INFO - 2024-12-27 17:48:32,536 - uvicorn.error - _serve - Started server process [215165]
INFO - 2024-12-27 17:48:32,538 - uvicorn.error - startup - Waiting for application startup.
ERROR - 2024-12-27 17:48:32,690 - uvicorn.error - send - Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/main.py", line 29, in lifespan
    await handler.on_api_start()
  File "/home/uti/Documents/FastAPI/api/src/handler.py", line 14, in on_api_start
    await db.create_tables()
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 64, in create_tables
    await self.create_admin_account(self.async_session)
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 78, in create_admin_account
    created_by=admin_username,
               ^^^^^^^^^^^^^^
NameError: name 'admin_username' is not defined

ERROR - 2024-12-27 17:48:32,692 - uvicorn.error - startup - Application startup failed. Exiting.
DEBUG - 2024-12-27 17:48:42,014 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:48:42,015 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
DEBUG - 2024-12-27 17:48:42,416 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.135891134997936'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.135891134997936'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc')}
INFO - 2024-12-27 17:48:42,436 - uvicorn.error - _serve - Started server process [215271]
INFO - 2024-12-27 17:48:42,438 - uvicorn.error - startup - Waiting for application startup.
INFO - 2024-12-27 17:48:42,599 - fastapi - create_admin_account - account with id cada1328-ae01-48bf-bbed-446a035cd9d9 created
ERROR - 2024-12-27 17:48:42,601 - uvicorn.error - send - Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/main.py", line 29, in lifespan
    await handler.on_api_start()
  File "/home/uti/Documents/FastAPI/api/src/handler.py", line 14, in on_api_start
    await db.create_tables()
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 64, in create_tables
    await self.create_admin_account(self.async_session)
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 87, in create_admin_account
    self.logger.info(f"Admin account with name {admin_username} exist already")
                                                ^^^^^^^^^^^^^^
NameError: name 'admin_username' is not defined. Did you mean: 'admin_user'?

ERROR - 2024-12-27 17:48:42,603 - uvicorn.error - startup - Application startup failed. Exiting.
DEBUG - 2024-12-27 17:48:42,766 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:48:42,767 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
DEBUG - 2024-12-27 17:48:43,168 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc'), (<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.128483209848240'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.128483209848240')}
INFO - 2024-12-27 17:48:43,208 - uvicorn.error - _serve - Started server process [215287]
INFO - 2024-12-27 17:48:43,210 - uvicorn.error - startup - Waiting for application startup.
INFO - 2024-12-27 17:48:43,370 - fastapi - create_admin_account - account with id a1950ff6-7f33-4e29-9fa7-c0f5d1b5bb8a created
ERROR - 2024-12-27 17:48:43,372 - uvicorn.error - send - Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/main.py", line 29, in lifespan
    await handler.on_api_start()
  File "/home/uti/Documents/FastAPI/api/src/handler.py", line 14, in on_api_start
    await db.create_tables()
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 64, in create_tables
    await self.create_admin_account(self.async_session)
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 87, in create_admin_account
    self.logger.info(f"Admin account with name {admin_username} exist already")
                                                ^^^^^^^^^^^^^^
NameError: name 'admin_username' is not defined. Did you mean: 'admin_user'?

ERROR - 2024-12-27 17:48:43,374 - uvicorn.error - startup - Application startup failed. Exiting.
DEBUG - 2024-12-27 17:48:55,954 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:48:55,954 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
DEBUG - 2024-12-27 17:48:56,355 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.132328066426288'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.132328066426288'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc')}
INFO - 2024-12-27 17:48:56,378 - uvicorn.error - _serve - Started server process [215390]
INFO - 2024-12-27 17:48:56,380 - uvicorn.error - startup - Waiting for application startup.
INFO - 2024-12-27 17:48:56,531 - fastapi - create_admin_account - account with id adcdc97d-7c1a-4e69-a7e0-3a85cc9a73db created
ERROR - 2024-12-27 17:48:56,533 - uvicorn.error - send - Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/main.py", line 29, in lifespan
    await handler.on_api_start()
  File "/home/uti/Documents/FastAPI/api/src/handler.py", line 14, in on_api_start
    await db.create_tables()
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 64, in create_tables
    await self.create_admin_account(self.async_session)
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 86, in create_admin_account
    self.logger.info(f"Admin account with name {admin_username} exist already")
                                                ^^^^^^^^^^^^^^
NameError: name 'admin_username' is not defined. Did you mean: 'admin_user'?

ERROR - 2024-12-27 17:48:56,534 - uvicorn.error - startup - Application startup failed. Exiting.
DEBUG - 2024-12-27 17:48:57,157 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:48:57,157 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
DEBUG - 2024-12-27 17:48:57,559 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.137720123106736'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.137720123106736'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc')}
INFO - 2024-12-27 17:48:57,585 - uvicorn.error - _serve - Started server process [215412]
INFO - 2024-12-27 17:48:57,588 - uvicorn.error - startup - Waiting for application startup.
INFO - 2024-12-27 17:48:57,747 - fastapi - create_admin_account - account with id d9e4ac88-fd53-473e-a506-af90bd836540 created
ERROR - 2024-12-27 17:48:57,748 - uvicorn.error - send - Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/main.py", line 29, in lifespan
    await handler.on_api_start()
  File "/home/uti/Documents/FastAPI/api/src/handler.py", line 14, in on_api_start
    await db.create_tables()
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 64, in create_tables
    await self.create_admin_account(self.async_session)
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 86, in create_admin_account
    self.logger.info(f"Admin account with name {admin_username} exist already")
                                                ^^^^^^^^^^^^^^
NameError: name 'admin_username' is not defined. Did you mean: 'admin_user'?

ERROR - 2024-12-27 17:48:57,750 - uvicorn.error - startup - Application startup failed. Exiting.
DEBUG - 2024-12-27 17:49:12,752 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:49:12,752 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
DEBUG - 2024-12-27 17:49:13,103 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.135341919380912'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.135341919380912'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc')}
INFO - 2024-12-27 17:49:13,169 - uvicorn.error - _serve - Started server process [215555]
INFO - 2024-12-27 17:49:13,171 - uvicorn.error - startup - Waiting for application startup.
INFO - 2024-12-27 17:49:13,309 - fastapi - create_admin_account - account with id 72893d0d-d959-4e20-8c5a-5ab680963c6c created
ERROR - 2024-12-27 17:49:13,311 - uvicorn.error - send - Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/main.py", line 29, in lifespan
    await handler.on_api_start()
  File "/home/uti/Documents/FastAPI/api/src/handler.py", line 14, in on_api_start
    await db.create_tables()
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 64, in create_tables
    await self.create_admin_account(self.async_session)
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 87, in create_admin_account
    self.logger.info(f"Admin account with name {admin_username} exist already")
                                                ^^^^^^^^^^^^^^
NameError: name 'admin_username' is not defined. Did you mean: 'admin_user'?

ERROR - 2024-12-27 17:49:13,312 - uvicorn.error - startup - Application startup failed. Exiting.
DEBUG - 2024-12-27 17:49:16,061 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:49:16,062 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
DEBUG - 2024-12-27 17:49:16,464 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.134126644962736'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.134126644962736')}
INFO - 2024-12-27 17:49:16,502 - uvicorn.error - _serve - Started server process [215593]
INFO - 2024-12-27 17:49:16,504 - uvicorn.error - startup - Waiting for application startup.
ERROR - 2024-12-27 17:49:16,687 - uvicorn.error - send - Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/main.py", line 29, in lifespan
    await handler.on_api_start()
  File "/home/uti/Documents/FastAPI/api/src/handler.py", line 14, in on_api_start
    await db.create_tables()
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 64, in create_tables
    await self.create_admin_account(self.async_session)
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 67, in create_admin_account
    admin
NameError: name 'admin' is not defined

ERROR - 2024-12-27 17:49:16,688 - uvicorn.error - startup - Application startup failed. Exiting.
DEBUG - 2024-12-27 17:49:18,268 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:49:18,268 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
DEBUG - 2024-12-27 17:49:18,670 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.124710250096048'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.124710250096048'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc')}
INFO - 2024-12-27 17:49:18,694 - uvicorn.error - _serve - Started server process [215603]
INFO - 2024-12-27 17:49:18,697 - uvicorn.error - startup - Waiting for application startup.
ERROR - 2024-12-27 17:49:18,834 - uvicorn.error - send - Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/main.py", line 29, in lifespan
    await handler.on_api_start()
  File "/home/uti/Documents/FastAPI/api/src/handler.py", line 14, in on_api_start
    await db.create_tables()
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 64, in create_tables
    await self.create_admin_account(self.async_session)
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 67, in create_admin_account
    admin_user
UnboundLocalError: cannot access local variable 'admin_user' where it is not associated with a value

ERROR - 2024-12-27 17:49:18,835 - uvicorn.error - startup - Application startup failed. Exiting.
DEBUG - 2024-12-27 17:49:22,936 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:49:22,936 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
DEBUG - 2024-12-27 17:49:32,465 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:49:32,465 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
DEBUG - 2024-12-27 17:49:32,867 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.127379115926960'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.127379115926960'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc')}
INFO - 2024-12-27 17:49:32,899 - uvicorn.error - _serve - Started server process [215790]
INFO - 2024-12-27 17:49:32,901 - uvicorn.error - startup - Waiting for application startup.
INFO - 2024-12-27 17:49:33,087 - fastapi - create_admin_account - account with id 3fdc5c55-4e6f-4c3b-95d1-b1eac8d81756 created
ERROR - 2024-12-27 17:49:33,089 - uvicorn.error - send - Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/main.py", line 29, in lifespan
    await handler.on_api_start()
  File "/home/uti/Documents/FastAPI/api/src/handler.py", line 14, in on_api_start
    await db.create_tables()
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 64, in create_tables
    await self.create_admin_account(self.async_session)
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 87, in create_admin_account
    self.logger.info(f"Admin account with name {admin_username} exist already")
                                                ^^^^^^^^^^^^^^
NameError: name 'admin_username' is not defined. Did you mean: 'admin_user'?

ERROR - 2024-12-27 17:49:33,090 - uvicorn.error - startup - Application startup failed. Exiting.
DEBUG - 2024-12-27 17:49:33,468 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:49:33,468 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
DEBUG - 2024-12-27 17:49:33,870 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.134278531261872'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.134278531261872')}
INFO - 2024-12-27 17:49:33,932 - uvicorn.error - _serve - Started server process [215803]
INFO - 2024-12-27 17:49:33,934 - uvicorn.error - startup - Waiting for application startup.
INFO - 2024-12-27 17:49:34,061 - fastapi - create_admin_account - account with id 0aac3410-c82c-449c-b322-866f9cb0add9 created
ERROR - 2024-12-27 17:49:34,062 - uvicorn.error - send - Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/main.py", line 29, in lifespan
    await handler.on_api_start()
  File "/home/uti/Documents/FastAPI/api/src/handler.py", line 14, in on_api_start
    await db.create_tables()
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 64, in create_tables
    await self.create_admin_account(self.async_session)
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 87, in create_admin_account
    self.logger.info(f"Admin account with name {admin_username} exist already")
                                                ^^^^^^^^^^^^^^
NameError: name 'admin_username' is not defined. Did you mean: 'admin_user'?

ERROR - 2024-12-27 17:49:34,064 - uvicorn.error - startup - Application startup failed. Exiting.
DEBUG - 2024-12-27 17:49:39,486 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:49:39,486 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
DEBUG - 2024-12-27 17:49:39,888 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc'), (<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.124415742010800'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.124415742010800')}
INFO - 2024-12-27 17:49:39,922 - uvicorn.error - _serve - Started server process [215893]
INFO - 2024-12-27 17:49:39,924 - uvicorn.error - startup - Waiting for application startup.
ERROR - 2024-12-27 17:49:40,066 - uvicorn.error - send - Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/main.py", line 29, in lifespan
    await handler.on_api_start()
  File "/home/uti/Documents/FastAPI/api/src/handler.py", line 14, in on_api_start
    await db.create_tables()
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 64, in create_tables
    await self.create_admin_account(self.async_session)
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 68, in create_admin_account
    admin
NameError: name 'admin' is not defined

ERROR - 2024-12-27 17:49:40,067 - uvicorn.error - startup - Application startup failed. Exiting.
DEBUG - 2024-12-27 17:49:42,445 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:49:42,445 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
DEBUG - 2024-12-27 17:49:42,846 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.140352349824432'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.140352349824432'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc')}
INFO - 2024-12-27 17:49:42,869 - uvicorn.error - _serve - Started server process [215926]
INFO - 2024-12-27 17:49:42,871 - uvicorn.error - startup - Waiting for application startup.
ERROR - 2024-12-27 17:49:43,035 - uvicorn.error - send - Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/main.py", line 29, in lifespan
    await handler.on_api_start()
  File "/home/uti/Documents/FastAPI/api/src/handler.py", line 14, in on_api_start
    await db.create_tables()
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 64, in create_tables
    await self.create_admin_account(self.async_session)
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 68, in create_admin_account
    admin_email
NameError: name 'admin_email' is not defined

ERROR - 2024-12-27 17:49:43,037 - uvicorn.error - startup - Application startup failed. Exiting.
DEBUG - 2024-12-27 17:49:45,503 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:49:45,503 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
DEBUG - 2024-12-27 17:49:45,904 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.123525492172208'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.123525492172208'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc')}
INFO - 2024-12-27 17:49:45,923 - uvicorn.error - _serve - Started server process [215961]
INFO - 2024-12-27 17:49:45,925 - uvicorn.error - startup - Waiting for application startup.
INFO - 2024-12-27 17:49:46,104 - fastapi - create_admin_account - account with id a099c245-7cb6-46fc-bf61-3281342de085 created
ERROR - 2024-12-27 17:49:46,105 - uvicorn.error - send - Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/main.py", line 29, in lifespan
    await handler.on_api_start()
  File "/home/uti/Documents/FastAPI/api/src/handler.py", line 14, in on_api_start
    await db.create_tables()
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 64, in create_tables
    await self.create_admin_account(self.async_session)
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 88, in create_admin_account
    self.logger.info(f"Admin account with name {admin_username} exist already")
                                                ^^^^^^^^^^^^^^
NameError: name 'admin_username' is not defined. Did you mean: 'admin_user'?

ERROR - 2024-12-27 17:49:46,107 - uvicorn.error - startup - Application startup failed. Exiting.
DEBUG - 2024-12-27 17:49:48,913 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:49:48,913 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
DEBUG - 2024-12-27 17:50:00,141 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:50:00,141 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
DEBUG - 2024-12-27 17:50:00,542 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc'), (<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.139384466974128'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.139384466974128')}
INFO - 2024-12-27 17:50:00,572 - uvicorn.error - _serve - Started server process [216114]
INFO - 2024-12-27 17:50:00,574 - uvicorn.error - startup - Waiting for application startup.
INFO - 2024-12-27 17:50:00,749 - fastapi - create_admin_account - account with id cf536e19-16c9-4c23-888d-f9312b4f7f41 created
ERROR - 2024-12-27 17:50:00,751 - uvicorn.error - send - Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/main.py", line 29, in lifespan
    await handler.on_api_start()
  File "/home/uti/Documents/FastAPI/api/src/handler.py", line 14, in on_api_start
    await db.create_tables()
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 64, in create_tables
    await self.create_admin_account(self.async_session)
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 88, in create_admin_account
    self.logger.info(f"Admin account with name {admin_username} exist already")
                                                ^^^^^^^^^^^^^^
NameError: name 'admin_username' is not defined. Did you mean: 'admin_user'?

ERROR - 2024-12-27 17:50:00,752 - uvicorn.error - startup - Application startup failed. Exiting.
DEBUG - 2024-12-27 17:50:02,648 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:50:02,649 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
DEBUG - 2024-12-27 17:50:03,050 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.136013601580464'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc'), (<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.136013601580464')}
INFO - 2024-12-27 17:50:03,088 - uvicorn.error - _serve - Started server process [216160]
INFO - 2024-12-27 17:50:03,090 - uvicorn.error - startup - Waiting for application startup.
INFO - 2024-12-27 17:50:03,236 - fastapi - create_admin_account - account with id ead37f30-376f-428f-b077-0fde8269916e created
ERROR - 2024-12-27 17:50:03,238 - uvicorn.error - send - Traceback (most recent call last):
  File "/home/uti/.cache/pypoetry/virtualenvs/e-shop_api-rkTj9SFp-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/uti/Documents/FastAPI/api/src/main.py", line 29, in lifespan
    await handler.on_api_start()
  File "/home/uti/Documents/FastAPI/api/src/handler.py", line 14, in on_api_start
    await db.create_tables()
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 64, in create_tables
    await self.create_admin_account(self.async_session)
  File "/home/uti/Documents/FastAPI/api/src/modules/database/base.py", line 88, in create_admin_account
    self.logger.info(f"Admin account with name {admin_username} exist already")
                                                ^^^^^^^^^^^^^^
NameError: name 'admin_username' is not defined. Did you mean: 'admin_user'?

ERROR - 2024-12-27 17:50:03,239 - uvicorn.error - startup - Application startup failed. Exiting.
DEBUG - 2024-12-27 17:50:27,773 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:50:27,774 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
DEBUG - 2024-12-27 17:50:28,175 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.128630064129456'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc'), (<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.128630064129456')}
INFO - 2024-12-27 17:50:28,224 - uvicorn.error - _serve - Started server process [216288]
INFO - 2024-12-27 17:50:28,226 - uvicorn.error - startup - Waiting for application startup.
INFO - 2024-12-27 17:50:28,400 - fastapi - create_admin_account - account with id 016f2b6b-1df7-4d14-b35f-dbfc83aa3e87 created
INFO - 2024-12-27 17:50:28,400 - fastapi - create_admin_account - Admin account with name elyte exist already
INFO - 2024-12-27 17:50:28,400 - fastapi - on_api_start - FastAPI Application: v1.0 is starting.
INFO - 2024-12-27 17:50:28,400 - uvicorn.error - startup - Application startup complete.
DEBUG - 2024-12-27 17:50:42,114 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:50:42,114 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
INFO - 2024-12-27 17:50:42,135 - uvicorn.error - shutdown - Shutting down
INFO - 2024-12-27 17:50:42,236 - uvicorn.error - shutdown - Waiting for application shutdown.
INFO - 2024-12-27 17:50:42,238 - fastapi - on_api_shuttdown - FastAPI Application: v1.0 is shutting down.
INFO - 2024-12-27 17:50:42,239 - uvicorn.error - shutdown - Application shutdown complete.
INFO - 2024-12-27 17:50:42,239 - uvicorn.error - _serve - Finished server process [216288]
DEBUG - 2024-12-27 17:50:42,643 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc'), (<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.135340324775344'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.135340324775344')}
INFO - 2024-12-27 17:50:42,671 - uvicorn.error - _serve - Started server process [216431]
INFO - 2024-12-27 17:50:42,673 - uvicorn.error - startup - Waiting for application startup.
INFO - 2024-12-27 17:50:42,821 - fastapi - create_admin_account - account with id af08bffd-0d12-4d66-b7c4-7c61216e3c3b created
INFO - 2024-12-27 17:50:42,821 - fastapi - create_admin_account - Admin account with name elyte exist already
INFO - 2024-12-27 17:50:42,821 - fastapi - on_api_start - FastAPI Application: v1.0 is starting.
INFO - 2024-12-27 17:50:42,821 - uvicorn.error - startup - Application startup complete.
DEBUG - 2024-12-27 17:50:52,867 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:50:52,867 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
INFO - 2024-12-27 17:50:52,946 - uvicorn.error - shutdown - Shutting down
INFO - 2024-12-27 17:50:53,047 - uvicorn.error - shutdown - Waiting for application shutdown.
INFO - 2024-12-27 17:50:53,049 - fastapi - on_api_shuttdown - FastAPI Application: v1.0 is shutting down.
INFO - 2024-12-27 17:50:53,049 - uvicorn.error - shutdown - Application shutdown complete.
INFO - 2024-12-27 17:50:53,050 - uvicorn.error - _serve - Finished server process [216431]
DEBUG - 2024-12-27 17:50:53,455 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.131656907384240'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc'), (<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.131656907384240')}
INFO - 2024-12-27 17:50:53,495 - uvicorn.error - _serve - Started server process [216534]
INFO - 2024-12-27 17:50:53,497 - uvicorn.error - startup - Waiting for application startup.
INFO - 2024-12-27 17:50:53,636 - fastapi - create_admin_account - account with id d0c08908-3690-4b46-a334-9c333365de04 created
INFO - 2024-12-27 17:50:53,636 - fastapi - create_admin_account - Admin account with name elyte exist already
INFO - 2024-12-27 17:50:53,636 - fastapi - on_api_start - FastAPI Application: v1.0 is starting.
INFO - 2024-12-27 17:50:53,636 - uvicorn.error - startup - Application startup complete.
DEBUG - 2024-12-27 17:51:07,992 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:51:07,992 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
INFO - 2024-12-27 17:51:08,084 - uvicorn.error - shutdown - Shutting down
INFO - 2024-12-27 17:51:08,184 - uvicorn.error - shutdown - Waiting for application shutdown.
INFO - 2024-12-27 17:51:08,188 - fastapi - on_api_shuttdown - FastAPI Application: v1.0 is shutting down.
INFO - 2024-12-27 17:51:08,188 - uvicorn.error - shutdown - Application shutdown complete.
INFO - 2024-12-27 17:51:08,188 - uvicorn.error - _serve - Finished server process [216534]
DEBUG - 2024-12-27 17:51:08,593 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.137267139388848'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.137267139388848'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc')}
INFO - 2024-12-27 17:51:08,642 - uvicorn.error - _serve - Started server process [216643]
INFO - 2024-12-27 17:51:08,646 - uvicorn.error - startup - Waiting for application startup.
INFO - 2024-12-27 17:51:08,800 - fastapi - create_admin_account - account with id 16b5f307-b1cf-4582-a9b6-329cbdf95379 created
INFO - 2024-12-27 17:51:08,800 - fastapi - create_admin_account - Admin account with name elyte exist already
INFO - 2024-12-27 17:51:08,800 - fastapi - on_api_start - FastAPI Application: v1.0 is starting.
INFO - 2024-12-27 17:51:08,800 - uvicorn.error - startup - Application startup complete.
DEBUG - 2024-12-27 17:51:11,501 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:51:11,501 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
INFO - 2024-12-27 17:51:11,510 - uvicorn.error - shutdown - Shutting down
INFO - 2024-12-27 17:51:11,611 - uvicorn.error - shutdown - Waiting for application shutdown.
INFO - 2024-12-27 17:51:11,614 - fastapi - on_api_shuttdown - FastAPI Application: v1.0 is shutting down.
INFO - 2024-12-27 17:51:11,614 - uvicorn.error - shutdown - Application shutdown complete.
INFO - 2024-12-27 17:51:11,614 - uvicorn.error - _serve - Finished server process [216643]
DEBUG - 2024-12-27 17:51:12,019 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc'), (<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.138412300068272'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.138412300068272')}
INFO - 2024-12-27 17:51:12,042 - uvicorn.error - _serve - Started server process [216717]
INFO - 2024-12-27 17:51:12,044 - uvicorn.error - startup - Waiting for application startup.
INFO - 2024-12-27 17:51:12,180 - fastapi - create_admin_account - account with id 3f7b2f7e-0503-49ae-90a9-3de62801e2a6 created
INFO - 2024-12-27 17:51:12,180 - fastapi - create_admin_account - Admin account with name elyte exist already
INFO - 2024-12-27 17:51:12,180 - fastapi - on_api_start - FastAPI Application: v1.0 is starting.
INFO - 2024-12-27 17:51:12,180 - uvicorn.error - startup - Application startup complete.
DEBUG - 2024-12-27 17:51:53,540 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/pyproject.toml')}
DEBUG - 2024-12-27 17:52:05,716 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:52:05,716 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
INFO - 2024-12-27 17:52:05,734 - uvicorn.error - shutdown - Shutting down
INFO - 2024-12-27 17:52:05,835 - uvicorn.error - shutdown - Waiting for application shutdown.
INFO - 2024-12-27 17:52:05,838 - fastapi - on_api_shuttdown - FastAPI Application: v1.0 is shutting down.
INFO - 2024-12-27 17:52:05,838 - uvicorn.error - shutdown - Application shutdown complete.
INFO - 2024-12-27 17:52:05,838 - uvicorn.error - _serve - Finished server process [216717]
DEBUG - 2024-12-27 17:52:10,205 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:52:10,205 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
DEBUG - 2024-12-27 17:52:13,066 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:52:13,067 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
DEBUG - 2024-12-27 17:52:20,385 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:52:20,385 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
DEBUG - 2024-12-27 17:52:20,787 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc'), (<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.135676496324016'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.135676496324016')}
INFO - 2024-12-27 17:52:20,823 - uvicorn.error - _serve - Started server process [217233]
INFO - 2024-12-27 17:52:20,825 - uvicorn.error - startup - Waiting for application startup.
INFO - 2024-12-27 17:52:21,004 - fastapi - create_admin_account - account with id 64c3f7a0-2de3-41e8-a891-fda08a34e57c created
INFO - 2024-12-27 17:52:21,004 - fastapi - create_admin_account - Admin account with name elyte exist already
INFO - 2024-12-27 17:52:21,004 - fastapi - on_api_start - FastAPI Application: v1.0 is starting.
INFO - 2024-12-27 17:52:21,004 - uvicorn.error - startup - Application startup complete.
DEBUG - 2024-12-27 17:52:27,806 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:52:27,807 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
INFO - 2024-12-27 17:52:27,829 - uvicorn.error - shutdown - Shutting down
INFO - 2024-12-27 17:52:27,930 - uvicorn.error - shutdown - Waiting for application shutdown.
INFO - 2024-12-27 17:52:27,933 - fastapi - on_api_shuttdown - FastAPI Application: v1.0 is shutting down.
INFO - 2024-12-27 17:52:27,933 - uvicorn.error - shutdown - Application shutdown complete.
INFO - 2024-12-27 17:52:27,933 - uvicorn.error - _serve - Finished server process [217233]
DEBUG - 2024-12-27 17:52:28,338 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.126387708306864'), (<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.126387708306864')}
INFO - 2024-12-27 17:52:28,370 - uvicorn.error - _serve - Started server process [217295]
INFO - 2024-12-27 17:52:28,372 - uvicorn.error - startup - Waiting for application startup.
INFO - 2024-12-27 17:52:28,523 - fastapi - create_admin_account - account with id e2ec428c-7f5c-404d-8c14-95fac63c7266 created
INFO - 2024-12-27 17:52:28,523 - fastapi - create_admin_account - Admin account with name elyte exist already
INFO - 2024-12-27 17:52:28,523 - fastapi - on_api_start - FastAPI Application: v1.0 is starting.
INFO - 2024-12-27 17:52:28,523 - uvicorn.error - startup - Application startup complete.
DEBUG - 2024-12-27 17:52:31,547 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:52:31,547 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
INFO - 2024-12-27 17:52:31,635 - uvicorn.error - shutdown - Shutting down
INFO - 2024-12-27 17:52:31,736 - uvicorn.error - shutdown - Waiting for application shutdown.
INFO - 2024-12-27 17:52:31,740 - fastapi - on_api_shuttdown - FastAPI Application: v1.0 is shutting down.
INFO - 2024-12-27 17:52:31,740 - uvicorn.error - shutdown - Application shutdown complete.
INFO - 2024-12-27 17:52:31,740 - uvicorn.error - _serve - Finished server process [217295]
DEBUG - 2024-12-27 17:52:32,145 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.127909913339312'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.127909913339312'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc')}
INFO - 2024-12-27 17:52:32,179 - uvicorn.error - _serve - Started server process [217374]
INFO - 2024-12-27 17:52:32,181 - uvicorn.error - startup - Waiting for application startup.
INFO - 2024-12-27 17:52:32,347 - fastapi - create_admin_account - account with id e65f7bbd-920c-4d1b-983d-99f43d153374 created
INFO - 2024-12-27 17:52:32,347 - fastapi - create_admin_account - Admin account with name elyte exist already
INFO - 2024-12-27 17:52:32,347 - fastapi - on_api_start - FastAPI Application: v1.0 is starting.
INFO - 2024-12-27 17:52:32,347 - uvicorn.error - startup - Application startup complete.
DEBUG - 2024-12-27 17:52:44,573 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 17:52:44,573 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
INFO - 2024-12-27 17:52:44,576 - uvicorn.error - shutdown - Shutting down
INFO - 2024-12-27 17:52:44,677 - uvicorn.error - shutdown - Waiting for application shutdown.
INFO - 2024-12-27 17:52:44,680 - fastapi - on_api_shuttdown - FastAPI Application: v1.0 is shutting down.
INFO - 2024-12-27 17:52:44,681 - uvicorn.error - shutdown - Application shutdown complete.
INFO - 2024-12-27 17:52:44,681 - uvicorn.error - _serve - Finished server process [217374]
DEBUG - 2024-12-27 17:52:45,086 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.139336275879344'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc'), (<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.139336275879344')}
INFO - 2024-12-27 17:52:45,147 - uvicorn.error - _serve - Started server process [217496]
INFO - 2024-12-27 17:52:45,149 - uvicorn.error - startup - Waiting for application startup.
INFO - 2024-12-27 17:52:45,305 - fastapi - create_admin_account - account with id 7386c906-6ff6-42d0-8c9b-5c6d71c9c907 created
INFO - 2024-12-27 17:52:45,305 - fastapi - create_admin_account - Admin account with name elyte exist already
INFO - 2024-12-27 17:52:45,305 - fastapi - on_api_start - FastAPI Application: v1.0 is starting.
INFO - 2024-12-27 17:52:45,305 - uvicorn.error - startup - Application startup complete.
DEBUG - 2024-12-27 18:08:37,905 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/pyproject.toml')}
DEBUG - 2024-12-27 18:08:42,418 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/pyproject.toml')}
DEBUG - 2024-12-27 18:09:41,091 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 18:09:41,092 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
INFO - 2024-12-27 18:09:41,139 - uvicorn.error - shutdown - Shutting down
INFO - 2024-12-27 18:09:41,240 - uvicorn.error - shutdown - Waiting for application shutdown.
INFO - 2024-12-27 18:09:41,243 - fastapi - on_api_shuttdown - FastAPI Application: v1.0 is shutting down.
INFO - 2024-12-27 18:09:41,243 - uvicorn.error - shutdown - Application shutdown complete.
INFO - 2024-12-27 18:09:41,243 - uvicorn.error - _serve - Finished server process [217496]
DEBUG - 2024-12-27 18:09:50,429 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 18:09:50,430 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
DEBUG - 2024-12-27 18:09:55,095 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 18:09:55,095 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
DEBUG - 2024-12-27 18:10:00,263 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 18:10:00,263 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
DEBUG - 2024-12-27 18:10:02,720 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 18:10:02,720 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
DEBUG - 2024-12-27 18:10:13,643 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 18:10:13,644 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
DEBUG - 2024-12-27 18:10:15,097 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 18:10:15,097 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
DEBUG - 2024-12-27 18:10:19,709 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 18:10:19,709 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
DEBUG - 2024-12-27 18:10:22,567 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 18:10:22,568 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
DEBUG - 2024-12-27 18:10:29,991 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 18:10:29,992 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
DEBUG - 2024-12-27 18:10:41,271 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 18:10:41,271 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
DEBUG - 2024-12-27 18:10:44,180 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 18:10:44,180 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
DEBUG - 2024-12-27 18:11:03,735 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/pyproject.toml')}
INFO - 2024-12-27 18:14:06,221 - uvicorn.error - shutdown - Stopping reloader process [211917]
INFO - 2024-12-27 18:14:08,000 - uvicorn.error - __init__ - Will watch for changes in these directories: ['/home/uti/Documents/FastAPI/api/src']
INFO - 2024-12-27 18:14:08,000 - uvicorn.error - bind_socket - Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO - 2024-12-27 18:14:08,001 - uvicorn.error - startup - Started reloader process [224216] using WatchFiles
INFO - 2024-12-27 18:14:08,419 - uvicorn.error - _serve - Started server process [224219]
INFO - 2024-12-27 18:14:08,421 - uvicorn.error - startup - Waiting for application startup.
INFO - 2024-12-27 18:14:08,573 - fastapi - create_admin_account - account with id 6ea0b6df-2396-48d8-b216-e10b973a286c created
INFO - 2024-12-27 18:14:08,573 - fastapi - create_admin_account - Admin account with name elyte exist already
INFO - 2024-12-27 18:14:08,573 - fastapi - on_api_start - FastAPI Application: v1.0 is starting.
INFO - 2024-12-27 18:14:08,573 - uvicorn.error - startup - Application startup complete.
DEBUG - 2024-12-27 18:15:23,213 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 18:15:23,214 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
INFO - 2024-12-27 18:15:23,218 - uvicorn.error - shutdown - Shutting down
INFO - 2024-12-27 18:15:23,319 - uvicorn.error - shutdown - Waiting for application shutdown.
INFO - 2024-12-27 18:15:23,322 - fastapi - on_api_shuttdown - FastAPI Application: v1.0 is shutting down.
INFO - 2024-12-27 18:15:23,322 - uvicorn.error - shutdown - Application shutdown complete.
INFO - 2024-12-27 18:15:23,323 - uvicorn.error - _serve - Finished server process [224219]
DEBUG - 2024-12-27 18:15:23,728 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc'), (<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.126710656214448'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.126710656214448')}
INFO - 2024-12-27 18:15:23,759 - uvicorn.error - _serve - Started server process [224584]
INFO - 2024-12-27 18:15:23,761 - uvicorn.error - startup - Waiting for application startup.
INFO - 2024-12-27 18:15:23,910 - fastapi - create_admin_account - account with id 03aaaeee-99cb-40d9-ab15-52c592ce7262 created
INFO - 2024-12-27 18:15:23,910 - fastapi - on_api_start - FastAPI Application: v1.0 is starting.
INFO - 2024-12-27 18:15:23,910 - uvicorn.error - startup - Application startup complete.
DEBUG - 2024-12-27 18:16:37,068 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/database/base.py')}
WARNING - 2024-12-27 18:16:37,068 - uvicorn.error - run - WatchFiles detected changes in 'modules/database/base.py'. Reloading...
INFO - 2024-12-27 18:16:37,138 - uvicorn.error - shutdown - Shutting down
INFO - 2024-12-27 18:16:37,239 - uvicorn.error - shutdown - Waiting for application shutdown.
INFO - 2024-12-27 18:16:37,243 - fastapi - on_api_shuttdown - FastAPI Application: v1.0 is shutting down.
INFO - 2024-12-27 18:16:37,243 - uvicorn.error - shutdown - Application shutdown complete.
INFO - 2024-12-27 18:16:37,243 - uvicorn.error - _serve - Finished server process [224584]
DEBUG - 2024-12-27 18:16:37,648 - watchfiles.main - _log_changes - 3 changes detected: {(<Change.deleted: 3>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.123574637684144'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc.123574637684144'), (<Change.added: 1>, '/home/uti/Documents/FastAPI/api/src/modules/database/__pycache__/base.cpython-312.pyc')}
INFO - 2024-12-27 18:16:37,680 - uvicorn.error - _serve - Started server process [224986]
INFO - 2024-12-27 18:16:37,682 - uvicorn.error - startup - Waiting for application startup.
INFO - 2024-12-27 18:16:37,726 - fastapi - create_admin_account - Admin account with name elyte exist already
INFO - 2024-12-27 18:16:37,727 - fastapi - on_api_start - FastAPI Application: v1.0 is starting.
INFO - 2024-12-27 18:16:37,727 - uvicorn.error - startup - Application startup complete.
DEBUG - 2024-12-27 18:20:35,604 - watchfiles.main - _log_changes - 1 change detected: {(<Change.modified: 2>, '/home/uti/Documents/FastAPI/api/src/modules/service/auth.py')}
WARNING - 2024-12-27 18:20:35,604 - uvicorn.error - run - WatchFiles detected changes in 'modules/service/auth.py'. Reloading...
INFO - 2024-12-27 18:20:35,665 - uvicorn.error - shutdown - Shutting down
INFO - 2024-12-27 18:20:35,765 - uvicorn.error - shutdown - Waiting for application shutdown.
INFO - 2024-12-27 18:20:35,766 - fastapi - on_api_shuttdown - FastAPI Application: v1.0 is shutting down.
INFO - 2024-12-27 18:20:35,766 - uvicorn.error - shutdown - Application shutdown complete.
INFO - 2024-12-27 18:20:35,766 - uvicorn.error - _serve - Finished server process [224986]
INFO - 2024-12-27 18:20:36,201 - uvicorn.error - _serve - Started server process [226093]
INFO - 2024-12-27 18:20:36,203 - uvicorn.error - startup - Waiting for application startup.
INFO - 2024-12-27 18:20:36,245 - fastapi - create_admin_account - Admin account with name elyte exist already
INFO - 2024-12-27 18:20:36,245 - fastapi - on_api_start - FastAPI Application: v1.0 is starting.
INFO - 2024-12-27 18:20:36,245 - uvicorn.error - startup - Application startup complete.
INFO - 2024-12-27 18:20:37,849 - uvicorn.error - shutdown - Shutting down
INFO - 2024-12-27 18:20:37,949 - uvicorn.error - shutdown - Waiting for application shutdown.
INFO - 2024-12-27 18:20:37,950 - fastapi - on_api_shuttdown - FastAPI Application: v1.0 is shutting down.
INFO - 2024-12-27 18:20:37,950 - uvicorn.error - shutdown - Application shutdown complete.
INFO - 2024-12-27 18:20:37,950 - uvicorn.error - _serve - Finished server process [226093]
INFO - 2024-12-27 18:20:37,954 - uvicorn.error - shutdown - Stopping reloader process [224216]
